<!DOCTYPE html>
<html lang="en">
<body>
    <?php
        loginRequired('dashboard');
        $dashboardController = new DashboardController;
    ?>

     <!-- Reset Password Modal -->
     <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true"> 
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Reset Password</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="alignCenter">
                        <div class="m-4">
                            <p>Please fill out this form to reset your password.</p>
                            <form action="<?php $dashboardController -> resetPassword($conn, $dashboardModel); ?>" method="post"> 
                                <div class="form-group">
                                    <label>New Password</label>
                                    <input type="password" name="new_password" class="form-control <?php echo (!empty($dashboardModel -> getNewPasswordErr())) ? 'is-invalid' : ''; ?> bg-secondary text-light" value="<?php echo $dashboardModel -> getNewPassword(); ?>">
                                    <span class="invalid-feedback"><?php echo $dashboardModel -> getNewPasswordErr(); ?></span>
                                </div>
                                <div class="form-group">
                                    <label>Confirm Password</label>
                                    <input type="password" name="confirm_password" class="form-control <?php echo (!empty($dashboardModel -> getConfirmPasswordErr())) ? 'is-invalid' : ''; ?> bg-secondary text-light">
                                    <span class="invalid-feedback"><?php echo $dashboardModel -> getConfirmPasswordErr(); ?></span>
                                </div>
                                <div class="form-group mt-2">
                                    <input type="submit" class="btn btn-success" value="Submit">
                                    <a class="btn btn-danger ms-2" href="dashboard">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <?php
        if(($dashboardModel -> getNewPasswordErr()) !== null){
            echo '<div class="alert alert-danger text-center">' .$dashboardModel -> getNewPasswordErr(). '</div>';
        }
        elseif(($dashboardModel -> getConfirmPasswordErr()) !== null){
            echo '<div class="alert alert-danger text-center">' .$dashboardModel -> getConfirmPasswordErr(). '</div>';
        }
    ?>
    <div class="panel m-3">
        <div id="gridcontainer">
            <div class="row grid-row">
                <div class="col-sm-3 mt-3">
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Reset Password</a>
                        <a href="#" class="list-group-item list-group-item-action">A second link item</a>
                        <a href="#" class="list-group-item list-group-item-action">A third link item</a>
                        <a href="#" class="list-group-item list-group-item-action">A fourth link item</a>
                    </div>
                </div>
                <div class="col-sm-9 mt-3">
                    
                </div>
            </div>
        </div>
    </div>
</body>
</html>