<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Layout</title>
    <link href="stylesheet.css" rel="stylesheet">
</head>
<body>
    <nav>
        <ul>
            <li>
                <a href="home" class="<?php echo $page == '/home' ? 'active' : ''; ?>"> Home </a>
            </li>
            <li>
                <a href="test1" class="<?php echo $page == '/test1' ? 'active' : ''; ?>"> Test Page 1 </a>
            </li>
            <li>
                <a href="test2" class="<?php echo $page == '/test2' ? 'active' : ''; ?>"> Test Page 2 </a>
            </li>
        </ul>
    </nav>
    <section id="main">
        <?php
            include $mainContent;
        ?>
    </section>
    <footer>
        This is footer.
    </footer>
</body>
</html>