<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo isset($title) ?  $title : $constants['APP_TITLE']; ?></title>
    <link rel="icon" type="image/x-icon" href="resources/favicon.png">
    <link href="resources/stylesheet.css" rel="stylesheet">
    <link href="resources/themes/<?php echo isset($variables['theme']) ? $variables['theme'] : 'default' ?>/stylesheet.css" rel="stylesheet">
</head>
<body class="p-2">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/home">Brand</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="test1" class="nav-link <?php echo $page == '/test1' ? 'active' : ''; ?>"> Test Page 1 </a>
                    </li>
                    <li class="nav-item">
                        <a href="test2" class="nav-link <?php echo $page == '/test2' ? 'active' : ''; ?>"> Test Page 2 </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Menu </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="login">Login</a></li>
                            <li><a class="dropdown-item" href="register">Sign Up</a></li>
                            <li><a class="dropdown-item" href="home?logout=true">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div style="padding-top:80px;"></div>
    <section id="main">
        <?php
            include $mainContent;
        ?>
    </section>
    <div style="padding-top:30px;"></div>
    <footer>
        <nav class="navbar fixed-bottom d-block p-2 navbar-dark bg-dark text-light text-center">This is footer</nav>   
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>