<!DOCTYPE html>
<html lang="en">
<body>
    <div style="display: flex;flex-wrap: wrap;justify-content: center;">
        <div class="wrapper">
            <?php
            // $isLoggedIn = $_GET['loggedIn'];
            // if($isLoggedIn == 'no'){
            //     echo '
            //     <div class="p-3 mb-2 bg-danger text-white p-2">You must login to continue</div>
            //     ';  
            // }
            ?>
            <h2 class="text-center">Login</h2>
            <p>Please fill in your credentials to login.</p>

            <?php 
            if(!empty($model -> getLogin_err())){
                echo '<div class="alert alert-danger">' . $model -> getLogin_err() . '</div>';
            }        
            ?>

            <form action="<?php $controller = new LoginController; $controller -> login($conn, $model); ?>" method="post">
                <div class="form-group">
                    <label>Username</label>
                    <input type="text" name="username" class="bg-secondary text-light form-control <?php echo (!empty($model -> getUsername_err())) ? 'is-invalid' : ''; ?>" value="<?php echo $model -> getUsername(); ?>">
                    <span class="invalid-feedback"><?php echo $model -> getUsername_err(); ?></span>
                </div>    
                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="password" class="bg-secondary text-light form-control <?php echo (!empty($model -> getPassword_err())) ? 'is-invalid' : ''; ?>">
                    <span class="invalid-feedback"><?php echo $model -> getPassword_err(); ?></span>
                </div>
                <div class="form-group pt-3 pb-3">
                    <input type="submit" class="btn btn-success" value="Login">
                </div>
                <p>Don't have an account? <a href="register" class="text-decoration-none">Sign up now</a></p>
            </form>
        </div>
    </div>
</body>
</html>